sudo: required
dist: trusty
language: node_js
node_js:
  - '8'

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - curl
      - libboost-system1.54.0
      - libboost-filesystem1.54.0
      - libboost-chrono1.54.0
      - libboost-program-options1.54.0
      - libboost-test1.54.0
      - libboost-thread1.54.0
      - libevent-pthreads-2.0
      - libdb5.1++
      - libminiupnpc8
      - libevent-2.0
      - libzmq3

cache:
  directories:
  - node_modules
  - $HOME/.npm/_prebuilds
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.cache/downloads

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - export TRUE_COMMIT_MESSAGES=$(git log --oneline -2 | grep "+build")
  - export TRUE_COMMIT=$(echo $TRUE_COMMIT_MESSAGES | awk '{print $1}')
  - echo $TRUE_COMMIT_MESSAGES
  - yarn install

script:
  - echo 'Build Dist' && echo -en 'travis_fold:start:script.build\\r'
  - yarn build --base-href="./"
  - echo -en 'travis_fold:end:script.build\\r'

  - echo 'Trailing Whitespace & Lint Codebase' && echo -en 'travis_fold:start:script.lint\\r'
  - ./contrib/trailing_whitespace.sh
  - yarn run lint
  - echo -en 'travis_fold:end:script.lint\\r'

  - echo 'Test Codebase' && echo -en 'travis_fold:start:script.test\\r'
  - yarn run travis:test
  - echo -en 'travis_fold:end:script.test\\r'

  - echo 'Package Test' && echo -en 'travis_fold:start:script.package\\r'
  - yarn run package:linux
  - echo -en 'travis_fold:end:script.package\\r'

  - if [[ $TRUE_COMMIT_MESSAGES == *"+build"* ]]; then ./nightly.sh; fi;

  - echo 'Done!'

# Disable coveralls for now
after_script:
  - npm run coveralls

#deploy:
#  - provider: releases
#    api-key:
#      secure: <>
#    file:
#      - $TRAVIS_BUILD_DIR/dist.zip
#      - $TRAVIS_BUILD_DIR/dist.zip.sha256sum.txt
#    overwrite: true
#    on:
#      tags: true
